import { createClient } from '@supabase/supabase-js'

// Ensure environment variables are set
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

if (!supabaseUrl) {
  throw new Error("Missing environment variable: NEXT_PUBLIC_SUPABASE_URL")
}
if (!supabaseAnonKey) {
  throw new Error("Missing environment variable: NEXT_PUBLIC_SUPABASE_ANON_KEY")
}

// Create a single supabase client for interacting with your database
export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// Define the type for a story generation record based on the database schema
export interface StoryGeneration {
    id?: string; // UUID generated by DB
    created_at?: string; // Timestamp generated by DB
    synopsis: string | null;
    style_note: string | null;
    requested_length: number | null;
    use_web_search?: boolean | null; // Optional in input, has default in DB
    prompt?: string | null; // The specific prompt sent to the LLM
    generated_story: string | null;
    parent_generation_id?: string | null; // For iterative refinement
    iteration_feedback?: string | null; // User feedback for refinement
    is_accepted?: boolean | null; // To mark the final accepted version
} 