// Define the type for a story generation record based on the database schema
export interface StoryGeneration {
    id?: string; // UUID generated by DB
    created_at?: string; // Timestamp generated by DB
    synopsis: string | null;
    style_note: string | null;
    requested_length: number | null;
    use_web_search?: boolean | null; // Optional in input, has default in DB
    prompt?: string | null; // The specific prompt sent to the LLM
    generated_story: string | null;
    parent_generation_id?: string | null; // For iterative refinement
    iteration_feedback?: string | null; // User feedback for refinement
    is_accepted?: boolean | null; // To mark the final accepted version
    user_id?: string | null; // Foreign key to auth.users (for logged-in users)
    user_identifier?: string | null; // For anonymous users (localStorage identifier)
} 